# Make file for 
#  guduz :  Yet another RED simulator (YaREDs)
#  Last Revised: October 2006  (M)
#     Mehmet Suzen  <mehmet.suzen@physics.org>  (M) 
#     Ziya Suzen  <zsuzen@acm.org>              (Z)
#
GCC=gcc-3.3
all:
	$(GCC) -g -ansi -Wall red.c -lm -lefence -o ../bin/red
clean:
	rm -f ../bin/red
