# Make file for 
#  guduz :  Yet another RED simulator (YaREDs)
#  Last Revised: October 2006  (M)
#     Mehmet Suzen  <mehmet.suzen@physics.org>  (M) 
#     Ziya Suzen  <zsuzen@acm.org>              (Z)
#
all:
	gcc -g -Wall red.c -lm -o ../bin/red
clean:
	rm -f ../bin/red
